### ISSUE TITLE
Bug: Error while sending command to a LoRaWan device

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#1045]
## Current Behavior
While trying to send a command to a connected sensor, here is (below) the issue I get in the Portal.

## Context (Environment)

**Portal version**: 2.7.0
**LoRaWAN Stack version**: 2.1

## Additional Information
![image](https://user-images.githubusercontent.com/33126264/183655478-f60474df-2454-4e64-81d9-fcf148bb8499.png)

**Comment by adcoly** [comment]
![image](https://user-images.githubusercontent.com/33126264/183660256-8d1af161-b7be-4b0d-aaf9-0b6ea7f7e628.png)

**Comment by adcoly** [comment]
This comes from a 400 response from the Function App.

**Comment by kbeaugrand** [comment]
@adcoly , I just release the v2.7.1 to fix the API version used by the portal to communicate with the Facade.

Furthermore, I added a new configuration option to specify in your deployment the API version to use. (by default ``2022-03-04`` which corresponds to the 2.1.0 release of LoRaWAN StarterKit).

Please, can you update your deployment to v2.7.1 to test this solution ?
