### ISSUE TITLE
Feature: Use Hangfire to handle and manage background and scheduled jobs

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#1079]
**Describe the solution you'd like**

Use [Hangfire](https://github.com/HangfireIO/Hangfire) to handle and manage background and scheduled jobs

Example: Hangfire can be use to trigger jobs to sync IoT Hub Portal database and Azure IoT Hub

### Remarks:
Jobs can be triggered as:
- Background jobs
- Scheduled/Cron
- Manually using Hangfire Dashboard or custom screen/api to interact with Hangfire

### Features to enable:
- [ ] To avoid data loss on the traceability of jobs; Use database to persist jobs infos and metadata related to Hangfire
- [ ] Enable Hangfire Dashboard (or create custom pages on IoT Hub Portal) to monitor and administer jobs
  - [ ] Secure access to Hangfire Dashboard: Only for Admins

**Comment by kbeaugrand** [comment]
Hangfire is under LGPL License. 

Would be preferable to use MIT licensed Framework to operate...
