### ISSUE TITLE
Feature: Add concentrator device Id in concentrator list

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#1101]
**Is your feature request related to a problem? Please describe.**
Same as #998 but for concentrators

**Describe the solution you'd like**
See #998 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by kbeaugrand** [comment]
@Metal-Mighty, please see the result here : 

![image](https://user-images.githubusercontent.com/9513635/185408473-0c1032cf-d3b7-414b-9446-f7c8c32345f1.png)
