### ISSUE TITLE
Bug: Renaming a device is only visible after a few minutes

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#1108]
## Expected Behavior
When renaming a device, the modifications should be visible right away

## Current Behavior
When renaming a device, the modifications aren't visible in the Portal until a few minutes (~3min). The device twin is updated correctly as soon as the saved button is pressed.

## Steps to Reproduce

1. Open a device details
2. Change its name and save
3. Go back to the list of devices
4. The device will still have the old name for a few minutes, then it will change

## Context (Environment)

**Portal version**: 2.7.1.73
**LoRaWAN Stack version**: 2.1.0

**Comment by kbeaugrand** [comment]
@Metal-Mighty, 

I can reproduce that on my side. However it seems that it takes less than 1min to have it changed on the list...
I'll look into IoT Hub query to see what is the expected cache from Azure...

**Comment by kbeaugrand** [comment]
@Metal-Mighty I have an answer from Microsoft about that case : 

> There can be a delay in returning Twins Query Results.  We give general guidance that if a Twins State does not update within 5 - 10 minutes; 10 minutes to be max.  You should open a support request with us. In general, after 10 minutes, you should have an updated Twin result.

Regarding that, I close this issue.

**Comment by kbeaugrand** [comment]
We will add an information in the popup to tell that list information might take some minutes to reflect the changes.
