### ISSUE TITLE
Change Gateway ID in Device Details to Gateway list (selectable)

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#1171]
### Discussed in https://github.com/CGI-FR/IoT-Hub-Portal/discussions/1150

<div type='discussions-op-text'>

<sup>Originally posted by **awesome-ideas[bot]** September  1, 2022</sup>
When specifying the Gateway identifier for a LoRaWAN device, it could be better to have an auto-complete select box that will help the user to better change this value.</div>

**Comment by kbeaugrand** [comment]
The Gateway ID is the device id that is running the LoRaWAN Network server module.

**Comment by hocinehacherouf** [comment]
Gateway ID should visible in device create view
