### ISSUE TITLE
Feature: Use Bicep to develop, build arm templates

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#1186]
We should: 
- Add a new pipeline to generate ARM template from Bicep
- This pipeline should download LoraWan Starter kit bicep deployment
- The pipeline will then test the ARM templates and archive that to a specific branch

Blocked by #1186

**Comment by kbeaugrand** [comment]
See [https://github.com/Azure/iotedge-lorawan-starterkit/issues/1884](https://github.com/Azure/iotedge-lorawan-starterkit/issues/1884)
