### ISSUE TITLE
Feature: Filter devices by device model

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#1242]
**Is your feature request related to a problem? Please describe.**
I would like to be able to filter devices to only show ones with a specific device model. Like in #991, specify a filter in the column header.

**Describe alternatives you've considered**
An alternative would be to select it from a drop down list in the search panel

**Additional context**

**Comment by hocinehacherouf** [comment]
The component `MudTable` used to list devices doesn't allow to add filters on header column.

There is another component [`MudDataGrid`](https://mudblazor.com/api/datagrid) that enables filtering by column but still in experimental state.
