### ISSUE TITLE
Bug: [CI] - Lint Documentation doesn't runs automatically

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#1245]
## Expected Behavior

Lint Documentation CI action should be triggered for each PR in docs/main. 

## Current Behavior

It's triggered when doing manual PRs. But automated PRs doesn't trigger the action even if it it required in the PR policies for the target branch.

## Steps to Reproduce

See https://github.com/CGI-FR/IoT-Hub-Portal/pull/1244 for example.

**Comment by hocinehacherouf** [comment]
There is a limitation on github to prevent infinite loop between ci job.

In our case, this bug results of the usage of the token secrets.GITHUB_TOKEN by task `peter-evans/create-pull-request@v4`.
We need to replace the token used `peter-evans/create-pull-request` by a scoped repo token to allow pull resquests to trigger any required workflows.

See : https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-536204092

**Comment by kbeaugrand** [comment]
@hocinehacherouf I send you in PM the App ID and credentials...
