### ISSUE TITLE
Feature: Catch all database exceptions

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#1247]
**Describe the solution you'd like**
All database exceptions must be translated to `InternalServerErrorException`

**Comment by kbeaugrand** [comment]
@hocinehacherouf , what about catching all unhandled exceptions in the ASP.NET core and translate it to ``InternalErrorException`` ?
This will help to reduce exception handling in our business code and ensure that exception are well catched at the end..

**Comment by kbeaugrand** [comment]
Discussed today: 
- Use a middleware to catch data base exceptions (
- Treat database exceptions and manage it to provide a more user friendly message to the user.

See [https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-6.0](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-6.0) for documentation about how writing a custom middleware.


In our case we will add custom maps to the ProblemDetailsMiddleware: 
ex: 
```
 // Add problem details support
            _ = services.AddProblemDetails(setup =>
            {
                setup.IncludeExceptionDetails = (_, _) => HostEnvironment.IsDevelopment();

                // Custom mapping function for FluentValidation's ValidationException.
                setup.MapFluentValidationException();

                setup.Map<InternalServerErrorException>(exception => new ProblemDetails
                {
                    Title = exception.Title,
                    Detail = exception.Detail,
                    Status = StatusCodes.Status500InternalServerError
                });

                setup.Map<BaseException>(exception => new ProblemDetails
                {
                    Title = exception.Title,
                    Detail = exception.Detail,
                    Status = StatusCodes.Status400BadRequest
                });

                setup.Map<ArgumentNullException>(exception => new ProblemDetails
                {
                    Title = "Null Argument",
                    Detail = exception.Message,
                    Status = StatusCodes.Status400BadRequest,
                    Extensions =
                    {
                        ["params"] = exception.ParamName
                    }
                });
            });

```

**Comment by kbeaugrand** [comment]
See [https://github.com/Giorgi/EntityFramework.Exceptions](https://github.com/Giorgi/EntityFramework.Exceptions) to provide a better way to catch EntityFramework exceptions.
