### ISSUE TITLE
Update AssetId and LocationCode

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#127]
Updating AssetId and Location code (the two fields shown below) a existing device does not work as expected.
![update_assteId_locationCode](https://user-images.githubusercontent.com/33126264/151515823-010ed7b8-f61d-47a4-b230-86862c6cc278.png)

I don't see any modification in the device twin of my sensor after applying updates.

**Comment by audserraCGI** [comment]
This error occurs when some required fields are missing (eg. Model Type, or AppEUI here)
I'm working on it!
