### ISSUE TITLE
Delete unused device model

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#128]
I can't delete an unused device model. This error occured :
![delete_unused_device_model](https://user-images.githubusercontent.com/33126264/151516705-1ef948bf-7d85-431b-87f2-c6da457922e7.png)

**Comment by audserraCGI** [comment]
Two different kinds of errors to deal with :
- When the model is falsely considered as used
- When the model doesn't have any picture
