### ISSUE TITLE
No image selected

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#130]
When there is no image selected for a device model, an URL is display in the device model detail
![no_image_selected_url](https://user-images.githubusercontent.com/33126264/151528746-e4d76844-ea6a-4086-9fef-1caef86d3fa7.png)
and nothing is displayed in the device list for those devices
![no_image_selected_device](https://user-images.githubusercontent.com/33126264/151528819-4b3d152f-fc33-4d70-940a-afafdd2d5ace.png)

Maybe it should display somethin else in those two locations.

**Comment by audserraCGI** [comment]
Update 
The problem is still here with the new UI :

![C2](https://user-images.githubusercontent.com/95615798/151933412-da625074-03ef-43f9-8cc3-1e46534649cb.PNG)
![C1](https://user-images.githubusercontent.com/95615798/151933413-f045a879-25fe-4047-bdd2-1cc49ce7aa8d.PNG)
