### ISSUE TITLE
Mark a wilcard in required fields

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#135]
**Is your feature request related to a problem? Please describe.**
Each required should be marked with a wilcard "*'

**Describe alternatives you've considered**
 - [x] New Device Model
 - [x] New Device
 - [x] Device Details
 - [x] Device Model Details
 - [ ] New Gateway

**Additional context**

**Comment by audserraCGI** [comment]
Use MudBlazor form validation & helper text
https://mudblazor.com/components/form#editform-support

**Comment by audserraCGI** [comment]
"Mark required fields in Gateway pages" moved to issue #163
