### ISSUE TITLE
Align UI button for adding device in gateway and device screens

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#140]
**Is your feature request related to a problem? Please describe.**
I saw that Add (device / device model and gateway) button is not the same between those screen.

Device List: 
![image](https://user-images.githubusercontent.com/9513635/151667828-143e4969-327c-403d-8a24-9567e1143dd2.png)

Gateway: 
![image](https://user-images.githubusercontent.com/9513635/151667841-59c09d42-d736-43a9-8c41-f164d7a07a46.png)

Device Models:
![image](https://user-images.githubusercontent.com/9513635/151667848-4ab86ef1-715f-48f1-aa1e-ccc968a91f13.png)

**Should also align the titles...**

**Describe the solution you'd like**
Have the same layout on buttons while navigating

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by audserraCGI** [comment]
On new UI, buttons are inconsistant from one page to another :

![C_CreateDevice](https://user-images.githubusercontent.com/95615798/151809792-c244da2f-b631-419b-ac46-58a7f3a729c0.PNG)
![C_CreateModel](https://user-images.githubusercontent.com/95615798/151809798-bb39e059-b85a-4439-b5a1-7c8db22f40ef.PNG)
![C_DeviceDetails](https://user-images.githubusercontent.com/95615798/151809802-f34cc42b-da12-422b-8a60-8e4465ae8bc0.PNG)
![C_DeviceModelDetail](https://user-images.githubusercontent.com/95615798/151809805-3cbc9334-a155-4831-91ad-1e1bf613b6f0.PNG)
