### ISSUE TITLE
Bug: When not specifying a concentrator thumbprint, empty string is added in twin

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#1409]
## Expected Behavior

When I add a new concentrator without any client thumbprint, the device twin should not have any thumbprint set.

## Current Behavior

The device twin have a thumbprint with empty string: 

<img width="364" alt="image" src="https://user-images.githubusercontent.com/9513635/197697768-edc92cf3-891c-4e2d-b42a-fcc6cc1b66ca.png">

## Steps to Reproduce

1. Create a new concentrator
2. Do not set any thumbprint
3. Save the concentrator

## Context (Environment)

**Portal version**: 3.3.0
**LoRaWAN Stack version**: N/A

**Comment by kbeaugrand** [comment]
Additional information: 
When not specifying, the clientThumbprints in the device model should not be present at all.

**Comment by audserraCGI** [comment]
The field should also be updated in the database:

**Npgsql.PostgresException (0x80004005): 23502: null value in column "ClientThumbprint" of relation "Concentrators" violates not-null constraint**
