### ISSUE TITLE
Refactoring : Remove TableClientFactory

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#1473]

**Comment by hocinehacherouf** [comment]
@kbeaugrand, We cannot remove TableClientFactory, it is used by seeders.

We have to maintain TableClientFactory until we no longer support data migration from azure storage account table to database.

**Comment by kbeaugrand** [comment]
The Table Client Factory was used during migration from v2 to v3. 
Since we are now in v4. We can achieve that?

**Comment by kbeaugrand** [comment]
Blocked by #1617
