### ISSUE TITLE
Feature: Split Startup configurations by layer

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#1543]
**Describe the solution you'd like**
Configurations of services and app must be delegated to the corresponding layers:

- Application:
  - Configuration of  Automapper
  - Configuration of services defined on this layer
  - ...
- Infrastructure
  - Configuration of database
  - Configuration of Authentication
  - Configuration of services defined on this layer
  - ...

**Comment by kbeaugrand** [comment]
Depends on #1256
