### ISSUE TITLE
Feature: Increase code coverage on DeviceListPage.razor

### ISSUE THREAD

**Issue by audserraCGI** [CGI-FR/IoT-Hub-Portal#1562]
PR #1483 doesn't cover new lines added on DeviceListPage.razor

Also the name of this function needs to be fixed:
https://github.com/CGI-FR/IoT-Hub-Portal/blob/634f85aef3f85706d52d64b671e2677cb8d8639e/src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Devices/DevicesListPageTests.cs#L298

**Comment by kbeaugrand** [comment]
The ``FliterBySelectModelShould`` should be renamed to ``TypingSomeCharactersInTheAutocompleteShouldFilterTheDeviceModels``
