### ISSUE TITLE
Bug: The redeploy of the portal with lorawan enabled fails on createIothubDevices step

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#1576]
On a redeploy senario, the template `lorawan-starterkit` fails on the step `createIothubDevices`  with message:

```json
{
    "status": "failed",
    "error": {
        "code": "DeploymentScriptError",
        "message": "The provided script failed without returning any errors. Please refer to https://aka.ms/DeploymentScriptsTroubleshoot for more deployment script information."
    }
}

**Comment by hocinehacherouf** [comment]
See: https://github.com/Azure/iotedge-lorawan-starterkit/issues/2061

**Comment by kbeaugrand** [comment]
@hocinehacherouf this might be fixed now

**Comment by hocinehacherouf** [comment]
@kbeaugrand it has been fixed but the lorawan-starterkit CLI has not been released yet. The bicep template of lorawan-starterkit is targeting the version 2.2.1 of the lorawan-starterkit CLI (Nov 8, 2022)
