### ISSUE TITLE
Feature: Add doc about new config keys required by device telemetry feature

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#1577]

**Comment by kbeaugrand** [comment]
Should we create a V4 for this feature also?

**Comment by kbeaugrand** [comment]
Please add a page to document how to migrate from V3 to v4 with screen shots

**Comment by hocinehacherouf** [comment]
> Please add a page to document how to migrate from V3 to v4 with screen shots

#1587
