### ISSUE TITLE
Spike: Implement reusable component on device details

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#1619]
## Description

To prepare the #1618. We decided to start by a technical spike dedicated on the device detail mpage.
The objective is to find the correct level of reusable component that we could implement to refactor our pages...

## Acceptance criteria

- [ ] More reusable components on the device detail page
- [ ] Maybe a specific/generic component for the structure of the page

**Comment by GuillaumeM-2ISA** [comment]
I carried out a feasibility study and the result is that the creation of a reusable component is possible.

**Comment by kbeaugrand** [comment]
> I carried out a feasibility study and the result is that the creation of a reusable component is possible.

Fine @GuillaumeM-2ISA.
Let close this spike now. 

Please create dedicated task that need to be realized to fulfil this objective
