### ISSUE TITLE
Update Gateway Detail page layout

### ISSUE THREAD

**Issue by audserraCGI** [CGI-FR/IoT-Hub-Portal#163]
**Is your feature request related to a problem? Please describe.**

The current pages still have fields in French.
Moreover, since Device and DeviceModel have been updated, Gateway pages should look like them.

![Capture](https://user-images.githubusercontent.com/95615798/152153032-f0e72610-1cd6-4e3c-831b-1fae5f8b2896.PNG)

**Describe the solution you'd like**

- [x] Update the layout
- [x] Translate missing fields
- [x] Add validation in form
- [x] Mark required fields with a wildcard

**Comment by kbeaugrand** [comment]
Todo: @kbeaugrand add a gateway deployment manifest for LoRa Gateways
