### ISSUE TITLE
Manage Non-LoRa Devices

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#171]
**Is your feature request related to a problem? Please describe.**
Get the possibility to manage devices that are not LoRa.

**Describe the solution you'd like**
Create a device model without LoRa specific fields.
- App EUI
- Sensor Decoder Url

Create a device based on this model, without LoRa Specifi fields:
- App EUI (from the model)
- App Key

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by audserraCGI** [comment]
Split the current models into two separate entities to segregate LoRa devices from non-LoRa devices.

![image](https://user-images.githubusercontent.com/95615798/153178017-02e98c6f-d735-4a15-a141-12fa6c2266db.png)
