### ISSUE TITLE
Bug: [E2E] - Move E2E test project code to src/

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#1776]
Related to #1485

## Expected Behavior

Move E2E test project code to src/

## Current Behavior

E2E test project source code is at the repository root. 

## Steps to Reproduce

N/A

## Context (Environment)

**Portal version**: N/A
**LoRaWAN Stack version**: N/A

**Comment by yassir-ai** [comment]
An errors have been generated when we add the E2E test project code to src.
When we put the E2E test project in solution folder but out of src,, it works
We have checked the presence of all the packages needed

**Comment by yassir-ai** [comment]
@kbeaugrand 
It's Ok now, we have solved this bug
