### ISSUE TITLE
Task: [E2E] Add E2E tests during Build & Test CI Action

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#1780]
Story: #1485 

**Description**
Modify the test task to run only unit test
Add a task to launch E2E test in the job

Exemple of a configuration: 
```
    - name: Run unit tests      
      run: dotnet test --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage" AzureIoTHub.Portal.Tests.Unit.csproj
      working-directory: src/

    - name: Run E2E tests
      run: dotnet test --no-build AzureIoTHub.Portal.Tests.E2E.csproj
      working-directory: src/
```

**Comment by Achraf-Git-dev** [comment]
We've used Github Actions to build an environment and run a simple Selenium test. However, we still only use Chrome to test the app, since Selenium can only perform a test on one browser at a time that we specify in the test code and that we install the driver package of. Do you think we might need some Driver Factory for this or is there another way?

**Comment by kbeaugrand** [comment]
Please make it work with chrome only at that time. 
We will discuss further for other browser options...

**Comment by kbeaugrand** [comment]
@Achraf-Git-dev could give me an update for this task ?

**Comment by Achraf-Git-dev** [comment]
@kbeaugrand The E2E tests run well on Github Actions. The only issue is that it takes time to establish a connection with local host, but in the end all the tests that are supposed to pass, do pass. We're not sure as to where these connection issues encountered at first originate from.

**Comment by kbeaugrand** [comment]
> @kbeaugrand The E2E tests run well on Github Actions. The only issue is that it takes time to establish a connection with local host, but in the end all the tests that are supposed to pass, do pass. We're not sure as to where these connection issues encountered at first originate from.

Is this issue transient ? What is the delay ? 

Fine if all the tests passes on this step.

On the current tests, I see : 
- Login
- Add/remove device models
- Add/remove devices

Is there other tests I didn't see ? 

1 scenario here: 
- Login
- Create device model
- Remove device model

Before creating the PR, please fix some things: 
- [ ] at [https://github.com/Achraf-Git-dev/IoT-Hub-Portal/blob/dd2cf485f26b930145a8895bd44d4cdb655bc820/src/AzureIoTHub.Portal.Tests.E2E/Pages/LoginPage.cs#LL25C84-L25C84](https://github.com/Achraf-Git-dev/IoT-Hub-Portal/blob/dd2cf485f26b930145a8895bd44d4cdb655bc820/src/AzureIoTHub.Portal.Tests.E2E/Pages/LoginPage.cs#LL25C84-L25C84), credentials should not be in the source code (nor in the config file)
- [ ] Take URL and credentials from the environment at [https://github.com/Achraf-Git-dev/IoT-Hub-Portal/blob/dd2cf485f26b930145a8895bd44d4cdb655bc820/src/AzureIoTHub.Portal.Tests.E2E/Pages/LoginPage.cs#LL20C33-L22C61](https://github.com/Achraf-Git-dev/IoT-Hub-Portal/blob/dd2cf485f26b930145a8895bd44d4cdb655bc820/src/AzureIoTHub.Portal.Tests.E2E/Pages/LoginPage.cs#LL20C33-L22C61) instead of config file.

Then if you can create a PR from what is present, if should be fine to use the PR to comment and adapt the code to what should be pushed on the official repo.

Regards,

**Comment by Achraf-Git-dev** [comment]
@kbeaugrand We added the credentials to Github secrets.

**Comment by yassir-ai** [comment]
@kbeaugrand You want us to do the PR now or until we add more scenarios?

**Comment by kbeaugrand** [comment]
@yassir-ai , if the PR can be done to add the E2E test during CI now. 

Other PRs can be done after with more scenarios

**Comment by kbeaugrand** [comment]
> @kbeaugrand We added the credentials to Github secrets.

Thanks, please add also the url by environment variable in the code. 
This url won't be passed from a github secret. you can pass it directly from the CI job

**Comment by Achraf-Git-dev** [comment]
> > @kbeaugrand We added the credentials to Github secrets.
> 
> Thanks, please add also the url by environment variable in the code. This url won't be passed from a github secret. you can pass it directly from the CI job

We added the URL to the environment variables. We're ready to do a PR

**Comment by yassir-ai** [comment]
@kbeaugrand 
The tests launched by GitHub CI worked on our fork (Achraf's fork) before doing the PR, but after doing it, the tests fail in the main CGI repository. 
Apparantly one of css element couldn't be selected during the pull request tests.

**Comment by kbeaugrand** [comment]
Thank you @yassir-ai .

I'm checking that and adapting it to the current workflow. 
I'll stay you in touch when ready to merge
