### ISSUE TITLE
Task: Add AmazonIoTClient and AmazonIotDataClient configurations to interact with AWS IoT services

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#1793]
**Is your feature request related to a problem? Please describe.**
IoT Hub Portal must be able to interact with AWS IoT services.

**Describe the solution you'd like**

- Install the nuget package [`AWSSDK.IoT`](https://www.nuget.org/packages/AWSSDK.IoT) on backend
- Create a new singleton of [`AmazonIoTClient`](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/IoT/TIoTClient.html). 
- Install the nuget package [`AWSSDK.IotData`](https://www.nuget.org/packages/AWSSDK.IotData) on backend
- Create a new singleton of [`AmazonIotDataClient`](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/IotData/TIotDataClient.html). 

Suggestion:

```csharp
// Get AWS infos from configuraiton
var accessKey = "changeme";
var secretAccessKey = "changeme";
var region = "changeme";

_ = services.AddSingleton(new AmazonIoTClient(accessKey, secretAccessKey, RegionEndpoint.GetBySystemName(region)));
_ = services.AddSingleton(new AmazonIotDataClient(accessKey, secretAccessKey, new AmazonIotDataConfig()));
```

**Comment by delager** [comment]
At runtime, for the creation of the DataClient, the SourceURL attribute is mandatory.
We can retrieve the URL from the Amazon Client, we must also specify the type of Endpoint (doc : https://docs.aws.amazon.com/iot/latest/apireference/API_DescribeEndpoint.html) : 

```
// Get AWS infos from configuraiton
var accessKey = "changeme";
var secretAccessKey = "changeme";
var region = "changeme";

var AWSIoTClient = new AmazonIoTClient(accessKey, secretAccessKey, RegionEndpoint.GetBySystemName(region));

// Retrieve the source url from the Amazon client
var endPoint = AWSIoTClient.DescribeEndpointAsync(new DescribeEndpointRequest
{
            EndpointType = "iot:Data-ATS"
}).Result;

// Create AWSIoTDataClient with the retrieved endpoint address
var AWSIoTDataClient = new AmazonIotDataClient(accessKey, secretAccessKey, new AmazonIotDataConfig
{
            ServiceURL = $"https://{endPoint.EndpointAddress}"
});

_ = services.AddSingleton(AWSIoTClient);
_ = services.AddSingleton(AWSIoTDataClient);
```

We also need to condition the creation of these Amazon singletons on the `Provider` key to make sure it is at AWS (which is specified in #1883). There should be no error if we are in Azure.
So I create this configuration here which should be used in #1925 & #1883
