### ISSUE TITLE
Task: List AWS Thing Types using pagination

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#1807]
**Is your feature request related to a problem? Please describe.**

Related to #1802, #1805 and #1806

- Users must be able to list and search thing types by
  - Name
  - Description
  - Tags
  - Searchable Attributes
- Users must also be able to sort thing types by name.
- Users must by able to navigate to the create view to add a new thing type
- Users must by able to navigate to the edit view to update/deprecate an existing thing type
- Users must by able to delete an existing deprecated thing type

Documentation: https://docs.aws.amazon.com/iot/latest/developerguide/thing-types.html

**Describe the solution you'd like**

Backend:
- Create/update a service that queries database to get thing types
  - Pagination must be used
  - Filter by name, description, tags and searchable attributes
  - Order by name and description
- Create a REST endpoint that allow HTTP clients to query thing types

Frontend:
- Add a method on service layer that calls the backend to query thing types
- Add a blazor component to
  - Display thing types in a table by order on Name and description colunms. Each row of this table contains
    - Delete button to delete a thing type (Only when it is deprecated)
    - Details button to navigate the thing type details view
  - Search by name, description, tags and searchable attributes

**Comment by kbeaugrand** [comment]
@ssgueye2 is this ready to review ? If yes, please move the PR to review : 
<img width="719" alt="image" src="https://github.com/CGI-FR/IoT-Hub-Portal/assets/9513635/cdaae361-5f74-4a4a-9ef3-46657cd595e0">

**Comment by ssgueye2** [comment]
> @ssgueye2 is this ready to review ? If yes, please move the PR to review : <img alt="image" width="719" src="https://user-images.githubusercontent.com/9513635/237083121-cdaae361-5f74-4a4a-9ef3-46657cd595e0.png">

Yee Hocine validated it. but the PR includes three tickets (Listing, Update & Delete Thing Type). So I finished the Task on the listing using pagiantion and now I am working on the tasks "delete thing type" and "update thing type"
