### ISSUE TITLE
Feature: Replace DisableRowsPerPage directive by HideRowPerPage new directive

### ISSUE THREAD

**Issue by GuillaumeM-2ISA** [CGI-FR/IoT-Hub-Portal#1828]
**Is your feature request related to a problem? Please describe.**
MudBlazor has deprecated the DisableRowsPerPage directive in MudTablePager component.

**Comment by kbeaugrand** [comment]
Two pages concerned : 

- \Devices\DeviceListPage.razor
- \DeviceConfigurations\DeviceConfigurationListPage.razor
