### ISSUE TITLE
Story: As a user, I want to configure IoT devices to connect with x509 certificates

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#1877]
## Description

The portal should provide users with the ability to configure their IoT devices to connect to IoT Hub using x509 certificates for authentication. This feature will enable users to establish secure connections between their IoT devices and IoT Hub using x509 certificates, which provide a higher level of security than traditional username/password authentication.
When generating the certificate, the private key is returned from AWS, and that's the last time AWS will return it. So we need to save it in AWS  Secret Manager for the portal to be able to display this private key in the future.
Thus, we need to add the AWS  Secret Manager to our infra-as-code scripts, and use it to store and retrieve the private key for each certificate.
The private key will be stored in the AWS Secret Manager, and the key will be {device-name}-private-key

## Acceptance criteria

- [ ] The IoT Hub Portal should allow users to generate x509 certificates for their IoT devices. These certificates should be unique to each device and should be generated securely within the portal.
- [ ] The IoT Hub Portal should provide a way for users to download the x509 certificates in order to be able to upload it to their IoT devices. 

## Tasks

- [x] #1978
- [x] #1979
- [x] #1980
- [x] #1981

**Comment by inkonito** [comment]
@kbeaugrand We need to discuss this story. For now, it is not clear what is needed.
