### ISSUE TITLE
Task: Think about the AWS deployment and configuration

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#1925]
US: #1863 

## Description

When deploying to production in Azure, we sue secrets in the ``ConnectionString`` part of the configuration. 
We should ensure to have a way to work with that once deployed in AWS or find a workaround.

#1883 required to implement this task

To do with #1929 ?

**Comment by kbeaugrand** [comment]
@hocinehacherouf will take a look about the configuration process in AWS and docker deployement.

**Comment by delager** [comment]
> > > @hocinehacherouf will take a look about the configuration process in AWS and docker deployement.
> > 
> > 
> > Connection strings exist only on Azure/dotnet world. There is no equivalent in AWS.
> > ## What we should do ?
> > 
> > * In AWS mode, the portal should load configurations and secrets from environment variables.
> > * These environment variables can be set (created/updated) during the deployment of the container on EC2
> > 
> > **Remark:** Later, we should use Amazon Secrets Manager to store the secrets and configurations of the portal
> 
> Thanks,
> 
> In that case we could simply have a conditional config handler:
> 
> * AzureProduction
> * AWSProduction
> * Development
> 
> As I understand, Development and AWS seems to be the same code ?
> 
> In the ConfigHandlerFactory, we might have t handle the logic of constructing the config handler base on the requested environment and provider. => maybe a custom extension ?

@kbeaugrand So if I understand correctly we fall back on task #1929?
Don't we close this task? Or did I miss the difference between the 2 tasks?
