### ISSUE TITLE
Task: Resource identification: Identify the resources required to run the portal on AWS.

### ISSUE THREAD

**Issue by inkonito** [CGI-FR/IoT-Hub-Portal#1939]
We need to identify the resources mandatory for the portal to run on AWS:

- S3 storage
- PostgreSQL Database
- EC2 (Elastic Container)
- Keycloak instance
- AWS IoT (nothing to do ?)
- Others ?

**Comment by kbeaugrand** [comment]
> We need to identify the resources mandatory for the portal to run on AWS:
> 
> * S3 storage
> * PostgreSQL Database
> * EC2 (Elastic Container)
> * Keycloak instance
> * AWS IoT (nothing to do ?)
> * Others ?

To my mind, Keycloak should not be part of the deployement. It's only part of our infrastructure for the demo, not for the "standard" deployment.
