### ISSUE TITLE
Task: Deployment and validation

### ISSUE THREAD

**Issue by inkonito** [CGI-FR/IoT-Hub-Portal#1941]
Deploy the CloudFormation script to create the required resources on AWS and validate that they are functioning correctly.

**Comment by hocinehacherouf** [comment]
@inkonito: To validate AWS CloudFormation templates, we can use the tool [AWS CloudFormation Linter | cfn-lint](https://github.com/aws-cloudformation/cfn-lint) within a CI job.

**Comment by kbeaugrand** [comment]
@delager @inkonito @hocinehacherouf @ssgueye2 is this tested ? might we close it now ?

**Comment by ssgueye2** [comment]
@kbeaugrand Yeah Raphael did it and it worked. i can retest it again if you want but it may take time

**Comment by kbeaugrand** [comment]
> @kbeaugrand Yeah Raphael did it and it worked. i can retest it again if you want but it may take time

since you realized this, someone else should test it and validate it. ;) ..

**Comment by kbeaugrand** [comment]
I tested the CF scripts, I had some changes to make. This has been provided in #2087
