### ISSUE TITLE
Task: Add a button on the README page to deploy the whole platform

### ISSUE THREAD

**Issue by inkonito** [CGI-FR/IoT-Hub-Portal#1943]
We want to add a button on the documentation to be able to initialize the portal deployment with just one click on AWS

**Comment by delager** [comment]
After analysis there is no similar thing on Amazon side to deploy via a button.
There is the creation of a link to create a stack from a template (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-create-stacks-quick-create-links.html) 
but Amazon constrains the URL to be a URL pointing to a template stored in an S3 :
`TemplateURL
Location of file containing the template body. The URL must point to a template (max size: 460,800 bytes) that's located in an Amazon S3 bucket. For more information, see Template anatomy.`


The simplest solution to satisfy the need is to add a link to the cloudformation template file and to inform the 2 ways to create resources via the template (AWS console or AWS CLI)
