### ISSUE TITLE
Task: Infra as code: Add AWS Secret Manager

### ISSUE THREAD

**Issue by inkonito** [CGI-FR/IoT-Hub-Portal#1978]
Add a Secret Manager instance to our infra as code scripts

**Comment by delager** [comment]
From what I have seen there is nothing to do in the infra as code part, only in the configuration part :

Install the nuget package [AWSSDK.SecretsManager](https://www.nuget.org/packages/AWSSDK.SecretsManager) on backend
Create a new singleton of [AmazonSecretsManagerClient](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SecretsManager/TSecretsManagerClient.html).

Suggestion:

// Get AWS infos from configuraiton
var accessKey = "changeme";
var secretAccessKey = "changeme";
var region = "changeme";

_ = services.AddSingleton(new AmazonSecretsManagerClient(accessKey, secretAccessKey, RegionEndpoint.GetBySystemName(region)));
