### ISSUE TITLE
Feature: Delete a thing type (device model)

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#2092]
**Is your feature request related to a problem? Please describe.**
Currently we only deprecate a thing type. Iot Hub Portal must be able to delete a thing type.

**Describe the solution you'd like**
To delete a thing type:

1. Deprecate the thing type
2. Remove any associated things by calling UpdateThing to change the thing type on any associated thing
3. Use DeleteThingType to delete the thing type

**Describe alternatives you've considered**

**Additional context**
On AWS console, when I try to delete a thing type after decrecating it, I got this error:

![image](https://github.com/CGI-FR/IoT-Hub-Portal/assets/10477425/b75b8a96-fead-4a17-bf7d-061be9a3d39a)

**Comment by kbeaugrand** [comment]
Fixed by #2192
