### ISSUE TITLE
Story: As a deployer, I want to provide a default list of IoT device models

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#217]
## Description

While deploying the solution, the deploy should provide some templates to the users that are validated.
He also need to update them if needed (when a device change, new commands available, ...).

End users may not be able to modify default templates after the installation.

However, in case of LoRa devices they should be able to add commands that are not present in the default template.

## Acceptance criteria

- [ ] Should be automatizable
- [ ] Can support adding new models
- [ ] Do not edit deployed models.
- [ ] Should be idempotent
- [ ] Document the solution

**Comment by kbeaugrand** [comment]
What are common and should be provided by the template (not-modifiable by user): 

- Name, 
- Picture,
- Description

For LoRa: 

- AppEUI,
- Sensor Decoder Url,
- Commands (but user cad add new commands)
- Other lora properties (that will be added in #191)

**Comment by kbeaugrand** [comment]
As a preconized solution : 

- API based solution (not deployment template) -> that are already existing
- To specify if a template and command can be modified, use a new filed "isBuiltin"
- Should document the APIs (Swagger)
