### ISSUE TITLE
Bug: Wrong frequencies in AU915 FSB 2

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#2194]
## Current Behavior
In [AU915 FSB2, line 54](https://github.com/CGI-FR/IoT-Hub-Portal/blob/3616bfb2705fde21c182d54d12936d2970d83397/src/AzureIoTHub.Portal.Infrastructure/RouterConfigFiles/AU_915_928_FSB_2.json#L54), the 1st frequency reference used to compute chan_multiSF_4/5/6/7 seems to be the wrong one.

You should have 917100000 instead of 917200000 regarding to the Regional Parameter Guide for LoRa.

## Additional information
Every frequency should be separate with 0.2 MHz.
Here is what you have at the moment:
![image](https://github.com/CGI-FR/IoT-Hub-Portal/assets/33126264/6c451830-6982-4242-8fc3-2888ae446cd7)

Here is what you will have according to the modification suggested above:
![image](https://github.com/CGI-FR/IoT-Hub-Portal/assets/33126264/fc79be9d-24b4-43d3-b501-5fba3ac91dbd)

**Comment by kbeaugrand** [comment]
Hi @adrienaury, Are you sure about that? 
Regarding the LoRa WAN specifications for AU915-928, channels starts from 915.2 MHz: 

<img width="397" alt="image" src="https://github.com/CGI-FR/IoT-Hub-Portal/assets/9513635/ccac4475-eda0-4b48-9bcc-1b8801d0fd07">


[https://lora-alliance.org/resource_hub/rp2-102-lorawan-regional-parameters/](https://lora-alliance.org/resource_hub/rp2-102-lorawan-regional-parameters/)
