### ISSUE TITLE
Feature: Handle deduplication configuration

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#304]
**Is your feature request related to a problem? Please describe.**
The deduplication strategy cannot be configured through the portal for concentrators or devices, but it is an important option to configure for us to avoid data duplication in our message bus

**Describe the solution you'd like**
Have a selector in which I can choose my deduplication strategy for my concentrator/device.

**Describe alternatives you've considered**
Currently the alternative is to add the configuration directly in the Device Twin on Azure

**Additional context**
Msft ADR on the topic: https://azure.github.io/iotedge-lorawan-starterkit/dev/adr/007_message_deduplication/

**Comment by kbeaugrand** [comment]
Should be handled in #191
