### ISSUE TITLE
Feature: Add a custom name for the portal

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#305]
**Is your feature request related to a problem? Please describe.**
We have several instances of the IoT Portal already deployed, and a lot more planned to deploy in the upcoming months (with a goal of 60+ instances). When we have several portals opened we can't differentiate them in our tabs, which can lead to mistakes or loss of time when trying to find the right instance.

**Describe the solution you'd like**
An easy solution would be to add the ability to set a custom instance name through environment variables that would be displayed in the page's title and in the header.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kbeaugrand** [comment]
See #370 for the implementation.
