### ISSUE TITLE
Bug: Commands cannot be modified after the device model's creation in v1.0.2

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#306]
## Expected Behavior
The LoRaWan tab should be visible with the ability to add and remove commands from a device model

## Current Behavior
Only the main tab with the name, description and picture is available, we can't change the commands associated with the model

## Steps to Reproduce
N/A

### Browser
Mozilla Firefox 91.1.0esr (32-bit)

### Container Operating System
Linux containers

#### Docker
N/A

## Logs
N/A

## Additional Information
![image](https://user-images.githubusercontent.com/5247527/155321494-f3f3a060-67b7-4aee-bd50-0264b5acf857.png)

**Comment by adcoly** [comment]
This device model has been created before the 1.0.2 and it does not have the "supportLoRaFeatures" tag. We just need to do an update with this tag to get the "LoRaWan" tab back and use command features again.

**Comment by kbeaugrand** [comment]
Saw in PBR today. 
This issue is due to missing tags on the device model.

The use have to manually add these tags to the device model.
