### ISSUE TITLE
Task: Display detailed error in a popup in debug environment

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#321]

**Comment by hocinehacherouf** [comment]
### Example of the UI/UX to implement this feature

When an http exception is catched, a snackbar with issue detail will show up:

![image](https://user-images.githubusercontent.com/10477425/169709505-2c289b90-1cde-4a04-8a97-9ca88924a6f4.png)

The snackbar requires user interaction to remove it:

1. Click on X to close the snackbar
2. Click on More Details button

If the user choose to click on the button `More Details`, a dialog will show up:

![image](https://user-images.githubusercontent.com/10477425/169709892-f981088c-1e66-4841-a325-624507f0dc90.png)

The expansion panel `Exception Details` is visible only on Development env. When a user choose the expand it, he will see all the exception stack, formatted as json:

![image](https://user-images.githubusercontent.com/10477425/169709909-aba809a0-484c-4108-99b8-c8015f59cd6f.png)
