### ISSUE TITLE
Bug: Sometimes, an error happens on loading screen

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#349]
## Expected Behavior
Redirection to the IAM login screen

## Current Behavior
Blank "loading" page, unhandled exception strip, and a stack trace in browser logs

## Steps to Reproduce

1.
2.
3.
4.

### Browser
Mozilla Firefox 91.1.0esr (32-bit)

### Container Operating System
Linux containers

#### Docker
N/A

## Logs
![image](https://user-images.githubusercontent.com/5247527/155943959-5f23e9a3-d17e-4365-9b3a-15738569e0b1.png)

 ## Additional information
There are no verified circumstances for when it happens, but in my case it was after coming back from a week end break.

**Comment by kbeaugrand** [comment]
Hi @Metal-Mighty ,

When this error occurs, could you provide us the previous Rest request response ?

**Comment by hocinehacherouf** [comment]
@Metal-Mighty , any update ?

**Comment by adcoly** [comment]
@Metal-Mighty and I did not encounter this problem for a while.
@hocinehacherouf @kbeaugrand you can close this issue.
