### ISSUE TITLE
Feature: When creating a device, in model selection list, show a part of the description after the name

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#352]
**Is your feature request related to a problem? Please describe.**
We add device models based on the model name of the sensor, which isn't always very clear for the end user. Since device models have a description field, I would like it, or part of it, to be shown after the model's name in the model selection drop-down when creating a device.

**Describe the solution you'd like**
Display the device model's description, possibly truncated, after the model's name in the model selection drop-down when creating a device. It can be displayed in a lighter color in order to keep the focus on the device's name.

**Describe alternatives you've considered**
Add a short description in the name itself, but it can get long if several sensors aren't quite the same but very close and we need to describe the sensor precisely.

**Additional context**

**Comment by audserraCGI** [comment]
Using the <ItemTemplate> example found [here](https://docs.telerik.com/blazor-ui/components/autocomplete/templates) we can obtain something like that:

![image](https://user-images.githubusercontent.com/95615798/161296272-3882336e-8585-4114-b9eb-db44653d96e8.png)

See also : [MudAutocomplete<T> API](https://mudblazor.com/api/autocomplete#properties)
