### ISSUE TITLE
Feature: Add a "quick add" option in the left navbar

### ISSUE THREAD

**Issue by audserraCGI** [CGI-FR/IoT-Hub-Portal#361]
**Describe the solution you'd like**
Add an option allowing to quickly add a new device/model directly from the navbar, without having to load all the devices' list.

**Additional context**
![image](https://user-images.githubusercontent.com/95615798/156135979-0147d76f-4423-4677-af7e-02a7d9e521cd.png)

**Comment by kbeaugrand** [comment]
@Metal-Mighty and @adcoly , could you help us to specify the menu re-organization needed ?

**Comment by kbeaugrand** [comment]
Please see #402  for the expected refactoring

**Comment by Metal-Mighty** [comment]
> @Metal-Mighty and @adcoly , could you help us to specify the menu re-organization needed ?

Done (and much more !) in #398
