### ISSUE TITLE
Task: Add more functional metrics from the portal to prometheus

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#376]

**Comment by kbeaugrand** [comment]
Please @adcoly and @Metal-Mighty , could you provide which metrics is usefull for you

**Comment by hocinehacherouf** [comment]
@adcoly @Metal-Mighty any update ?

**Comment by kbeaugrand** [comment]
@adcoly @Metal-Mighty Up ?

**Comment by kbeaugrand** [comment]
- [ ] Number of devices
- [ ] Number of connected devices 
- [ ] ...
