### ISSUE TITLE
Bug: Creating an iot edge

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#380]
## Expected Behavior
I should be able to create a new IoT Edge through the portal

## Current Behavior
An error occurs saying the creation failed (see 1st screenshot below)

## Context (Environment)

**Portal version**: 1.0.3

## Logs
![create_iot_edge](https://user-images.githubusercontent.com/33126264/156728038-d26a7420-2da6-4719-a6db-aed554efa5a9.png)

Here is also the few information coming from the application insight
![create_iot_edge_appi](https://user-images.githubusercontent.com/33126264/156728136-903ebb8e-aba2-4ac3-9b78-d01c6dc78901.png)

**Comment by Metal-Mighty** [comment]
![image](https://user-images.githubusercontent.com/5247527/156729106-bb8dc908-a64f-444d-9879-8a08c1bb2eec.png)

**Comment by adcoly** [comment]
Fixed in 1.0.4
