### ISSUE TITLE
Bug: Enrollment group creation based on device model name

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#413]
## Expected Behavior

When I create a new device model, the enrollment created should have its name based on the model id and not the model name.
When I update the name of a device model, this should not create a new enrollement group for the same device model.

## Context (Environment)

**Portal version**: 1.0.4

## Logs
Json used to create a device model that triggered an error :
![model_json](https://user-images.githubusercontent.com/33126264/157479507-38f4d728-2b23-4843-b282-bc9632fd072b.png)

**Comment by adcoly** [comment]
Additional information:
Here is the error after a curl command on the web API :
![deploy_model_nke](https://user-images.githubusercontent.com/33126264/157479961-2ee7e6e5-fd6d-41cd-8b66-83c436b191c9.png)

Here is a json file that does not triggered any error:
![model_json_np](https://user-images.githubusercontent.com/33126264/157480030-0b956194-77ae-4129-be81-97339de8cbec.png)

Here is the location where the enrollment group is created in the code :
https://github.com/CGI-FR/IoT-Hub-Portal/blob/a620915ba790368bde5071f821b45ead648430a1/src/AzureIoTHub.Portal/Server/Managers/DeviceProvisioningServiceManager.cs#L43

**Comment by kbeaugrand** [comment]
Discussed today : 

- [ ] Create the enrollment group with the device model ID instead of the model name
