### ISSUE TITLE
Feature: Enhance landing page ("Loading..." text)

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#492]
**Is your feature request related to a problem? Please describe.**
When reaching the portal the user first lands on a blank page with the "Loading..." text on the upper left corner which isn't very visual, and there is no indication that the page is actually going to redirect later.

**Describe the solution you'd like**
- [ ] "Beautify" the page, maybe with a design close to the main portal design
- [ ] Add a loading animation

**Comment by hocinehacherouf** [comment]
Duplicate #560
