### ISSUE TITLE
Bug: Inconsistent loading animation on various (list) pages

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#509]
## Expected Behavior
When opening a page I expect the loading animations to be the same on every page

- [x] #520
- [x] #521
- [x] #522
- [x] #523

## Current Behavior
Different pages have different loading animations:
* Devices list: Loading animation in the table (good looking !)
* Device models: Round loading indicator in the top left, the table only appears after the data is loaded
* IoT Edge list: No animation, the table says there are "No matching records found" but it updates afterwards
* IoT Edge configuration: Same as device models
* Concentrators: Same as IoT Edge list
* Device tags: Same as device models

## Context (Environment)

**Portal version**: 1.0.6

**Comment by kbeaugrand** [comment]
Should add to MudTable the corresponding lines: 

```            
            <LoadingContent>
                <MudText>Loading...</MudText>
            </LoadingContent>
```

And add the Loading info to the MudTable: 
``` Loading="@_loading"```

**Comment by audserraCGI** [comment]
There seems to be an inconsistent behaviour between DeviceList and other pages (like ConcentratorList or IoTEdgeList).

Despite the pages having the exact same code, the former is showing loading progression, whereas the latter aren't.

I'm not sure what is happening exacty, but I may have found an explanation here: [https://github.com/MudBlazor/MudBlazor/pull/3711](https://github.com/MudBlazor/MudBlazor/pull/3711)

**Comment by kbeaugrand** [comment]
Added #563
