### ISSUE TITLE
Task: Add loading content to Concentrator list page

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#522]
Feature #509

**Comment by audserraCGI** [comment]
There seems to be an inconsistent behaviour between DeviceList and ConcentratorList pages.

Despite the pages having the **exact same code**, one is showing loading progression, whereas the second one isn't.

I'm not sure what is happening exacty, but I may have found an explanation here: [https://github.com/MudBlazor/MudBlazor/pull/3711](https://github.com/MudBlazor/MudBlazor/pull/3711)
