### ISSUE TITLE
Feature: Add in the API the possibility to add custom tags

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#530]
**Is your feature request related to a problem? Please describe.**
After a talk with @audserraCGI, it seems the current command available for creating/updating custom tags is deleting/purging all the previously created custom tags.

**Describe the solution you'd like**
I would like to have a command that allow me add a new custom tags without deleting the previous one.

**Describe alternatives you've considered**
Currently, I can push every tag I need every time I want to do an update.

**Additional context**
Current available command :
![image](https://user-images.githubusercontent.com/33126264/161014987-107af6c7-86c4-4053-acb8-2f88c3f82606.png)

**Comment by kbeaugrand** [comment]
Saw in PBR : 

- [ ] Add a PATCH method to add or update existing tags
- [ ] Add a DELETE method to delete existing tags

Tags should be unique by name, so the name will be considered as the identifier.
