### ISSUE TITLE
Bug: Client certificate Thumbprint badly reported in Device Twin

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#538]
## Expected Behavior
![image](https://user-images.githubusercontent.com/33126264/161263406-00bb4940-f0a9-4400-b8a1-d69b6788a6aa.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/33126264/161263520-2c0e89c3-6cb3-4292-910d-fb781911105a.png)

## Context (Environment)

**Portal version**: 1.0.7
**LoRaWAN Stack version**: 2.0

## Additional Information
![image](https://user-images.githubusercontent.com/33126264/161263283-9a64f3b2-77d4-4848-8d34-188d924f8e75.png)

**Comment by kbeaugrand** [comment]
TODO : Add thumprint format validation.

**Comment by kbeaugrand** [comment]
Exemple for certificate thumbprint: **1E:16:CC:3F:84:2F:65:FC:C0:AB:93:2D:63:8A:C6:4A:95:C9:1B:7A**
