### ISSUE TITLE
Bug: Device creation from LoRa device model doesn't work properly

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#551]
## Expected Behavior
Selecting a LoRa device model should allow us to input OTAA values and save as a LoRa device using OTAA.

## Current Behavior
* Device model selection isn't kept when switching to LORAWAN tab
* LORAWAN tab shows APB fields
* Device is saved with `useOTAA` set to `False`

## Steps to Reproduce

1. Create a new device
2. Select a LoRaWAN device model

## Context (Environment)

**Portal version**: 1.0.7
**LoRaWAN Stack version**: 2.0.0

## Additional Information
![image](https://user-images.githubusercontent.com/5247527/161994665-9827621a-c5c3-45dd-afd1-3467fa24630c.png)

**Comment by Metal-Mighty** [comment]
Not fixed in 1.0.8
![image](https://user-images.githubusercontent.com/5247527/162711976-831bc88d-49f5-46e8-96c8-e130854d491a.png)

**Comment by kbeaugrand** [comment]
@Metal-Mighty and @adcoly , 

This seems to be fixed and not reproductible with v1.2.0. Could you confirm ?

**Comment by Metal-Mighty** [comment]
All good !
