### ISSUE TITLE
Spike: Define technical design for a splash screen

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#560]
Todo : 
- Explain what is feasible
- Show cases

**Comment by hocinehacherouf** [comment]
# How ?
To implement a splash screen in a blazor wasm project, We have to replace the content of block `<div id="app">` (in the file [index.html](https://github.com/CGI-FR/IoT-Hub-Portal/blob/ddf40954180df6156dc13c40a63b726d5673da1d/src/AzureIoTHub.Portal/Client/wwwroot/index.html#L30)) with the the desired splash screen behaviour.

Example: https://darthpedro.net/2021/03/17/how-to-create-blazor-app-splash-screen/

# Constraints

* The splash screen must be implemented in pure html/css without using blazor componenets
* If the splash screen requires external resources (css, images, fonts...), the netwrok footprint must be low

**Comment by hocinehacherouf** [comment]
@kbeaugrand , a gif of the proposed splash screen:

![splash-screen](https://user-images.githubusercontent.com/10477425/163333147-30c56a7a-cd0f-499d-9243-9efbbd414d37.gif)

**Comment by kbeaugrand** [comment]
@hocinehacherouf , coule we use the same progress bar as présent on the app? 
Furthermore, is it possible to have the same logo on the app' primary color ?

**Comment by hocinehacherouf** [comment]
> @hocinehacherouf , could we use the same progress bar as present on the app? Furthermore, is it possible to have the same logo on the app' primary color ?

@kbeaugrand , new draft: I used the primary color on the logo + a progress bar on the top

![splash-screen](https://user-images.githubusercontent.com/10477425/163359627-023c0071-cd51-4c0e-920d-8b692c87a136.gif)

**Comment by kbeaugrand** [comment]
Could you place the progress bar below the logo, not across the entire width?

**Comment by kbeaugrand** [comment]
Yeahh!!
