### ISSUE TITLE
Feature: Clarify tags in device model documentation

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#575]
## Description
As a user, I would like to have a clear definition of the uses and utility of each tags listed in the documentation for a device model creation through the API.
It could be interesting to have a list of those that are mandatory for a basic device model.
It could also be great to have default value of each tags (in the screen below, describing all those tags, for example).

![image](https://user-images.githubusercontent.com/33126264/162763826-ba73f282-f309-4fcf-a123-12fb5eb3332d.png)

**Comment by kbeaugrand** [comment]
The default values information are tracked in #579
