### ISSUE TITLE
Bug: IoT Edge module logs pagination doesn't work

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#591]
## Expected Behavior
I would like to be able to browse through logs of my IoT Edge modules directly from the IoT Hub Portal.
A more streamlined interface would also be nice.

## Current Behavior
Only the last 10 logs are displayed and it's not possible to switch to other log pages
Also, the log window is very small and cramped and not pleasant to use.

## Context (Environment)

**Portal version**: 1.0.8
**LoRaWAN Stack version**: 2.0.0

**Comment by hocinehacherouf** [comment]
The C2C command `GetModuleLogs` doesnt propose any pagination mechanism (see: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-retrieve-iot-edge-logs?view=iotedge-2020-11)

@Metal-Mighty we can increase the maximum number of recovered logs from 10 to 200 with pagination on client side. What do you think ?
