### ISSUE TITLE
Bug: Scope Id is not displayed

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#597]
## Expected Behavior
When I click on the "connect" button in the concentrator detail, I should see the scope ID.

## Current Behavior
Nothing is displayed in the scope Id field.

## Context (Environment)
**Portal version**: 1.0.8

## Logs
![image](https://user-images.githubusercontent.com/33126264/163393639-fc8aaae9-3d5f-4499-9dad-b436c97babf4.png)

**Comment by kbeaugrand** [comment]
@adcoly , 

The value is coming from the portal settings. 
Do the portal have the ``IoTDPS__IDScope`` parameter set ?

**Comment by adcoly** [comment]
It works well with this parameter.
Thank you !
