### ISSUE TITLE
Keep the left column static/always visible, only the right column should be scrollable

### ISSUE THREAD

**Issue by Sben65** [CGI-FR/IoT-Hub-Portal#615]

**Comment by audserraCGI** [comment]
The new feature is not consistent on every page.

For example, on Create Device, the whole page is scrollable.

**Comment by hocinehacherouf** [comment]
@audserraCGI , this issue is only for device/model details pages.

@ChristopheRib63  will add the scrolling behavior on device/model creation pages.
