### ISSUE TITLE
Have a choice between "Save", "Save and Duplicate", "Save and add new" for users who will need to create a lot of devices 

### ISSUE THREAD

**Issue by Sben65** [CGI-FR/IoT-Hub-Portal#616]

**Comment by adcoly** [comment]
![tmp](https://user-images.githubusercontent.com/33126264/164423367-a4f59a5b-a062-40a4-8ff1-bd488ec5c238.png)

**Comment by hocinehacherouf** [comment]
Clone behaviour must be defined with @adcoly

**Comment by kbeaugrand** [comment]
Some fields should be empty : 

- Device Id
- Lorawan App Key

Device name should be copied with ``- copy`` suffix

Other fields should be copied
