### ISSUE TITLE
Bug: Error when saving non-LoRa device

### ISSUE THREAD

**Issue by audserraCGI** [CGI-FR/IoT-Hub-Portal#631]
## Expected Behavior
Pressing the "save changes" button should correctly update the device.

## Current Behavior

When updating a **non-LoRa device**, a error occurs (500 - Internal server error).

## Additional Information

Here's the information available in the "Network" section of the browser console:

![Capture](https://user-images.githubusercontent.com/95615798/165325814-61f32970-685f-447b-88fa-4be7706760f9.PNG)

The issue seems to come from unauthorized characters (dot) in the device property's name, in the Azure storage table below:

![image](https://user-images.githubusercontent.com/95615798/165326242-150b6ce5-7897-4a47-a8a9-750ab26ac4d1.png)

**Comment by hocinehacherouf** [comment]
The control characters '.', '$', '#', or ' ' must be prohibited to input within a property name on a non lora device.

Example of an input helper on property name field:

![image](https://user-images.githubusercontent.com/10477425/165796023-18de3b07-0bae-4404-ba7e-0d17840e0bc4.png)

**Remark :** On device model detail page, if the model's properties contains the prohibited control characters, the web app freezes 😞

This will lead us to on how to correct existing data ?
