### ISSUE TITLE
Feature: Add the "confirmed" tag for command sent to sensors

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#641]
**Is your feature request related to a problem? Please describe.**
It could be interesting to gives the possibility to ask for the confirmation of a sensor when a command is sent to it.

**Describe the solution you'd like**
I would like to have a "confirmed" checkbox for each of the created command : 
- if it is left empty, it send a command as it is sending it right now
- if it is checked, it send a command with a new tag in the json

**Additional context**
Here is an example of what I imagined for this :
![confirmed command example](https://user-images.githubusercontent.com/33126264/165949848-dc4e4ae2-2549-4179-b862-c1086da78b6d.png)

Here is an example of a json that can be send with the "confirmed" tag : 
`{
    "fport": 7,
    "confirmed": true,
    "rawpayload": "ARMDhAOEAQDIAMg="
}`

**Comment by kbeaugrand** [comment]
@adcoly and @Metal-Mighty , 

Should we use by default confirmed to true or not ?
