### ISSUE TITLE
Spike: Define the technical solution to scroll only the right part (Device details and Model)

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#727]
## Description

See #615

## Acceptance criteria

- [ ] Scroll only the right part
- [ ] Keep the left part visible (Image + buttons)
- [ ] Respect responsive design

**Comment by hocinehacherouf** [comment]
On the pages device details and device model details, the right part contains a tab component. The content of this component contains data that can grow (commands, properties...)

The best approach of better UX is to only make the content of the tab component scrollable.

### How to proceed ?

First we have to define a css class to specify the scroll configuration on the content of the tab component:

```css
.scrollable-tab-content {
    overflow-x: hidden;
    height: 60vh;
}
```

Then, on the component `MudTabs`, we have to add the css class `scrollable-tab-content` on the parameter `PanelClass`:

```razor
<MudTabs PanelClass="scrollable-tab-content">
</MudTabs>
```

### Result:

![scroll](https://user-images.githubusercontent.com/10477425/171055375-987080ef-ccf8-4979-b503-cf9118fe6be6.gif)
