### ISSUE TITLE
Feature: Move snackbar to bottom left position

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#745]
**Is your feature request related to a problem? Please describe.**
Currently, the snackbar is positioned at the top right of the screen, overlapping other elements requiring user interactions.

**Describe the solution you'd like**
Move snackbar to bottom left position

**Comment by kbeaugrand** [comment]
See [https://material.io/components/snackbars#placement](https://material.io/components/snackbars#placement) for more information

**Comment by kbeaugrand** [comment]
```cs
            _ = builder.Services.AddMudServices(opts => opts.SnackbarConfiguration.PositionClass = Defaults.Classes.Position.BottomLeft);
```

Snippet can be used in Program.cs for client.
