### ISSUE TITLE
Feature: Allow users to be able to add labels on devices and edge devices

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#777]
Labels will be used as functional metadata on devices and iot edge devices. The purpose of labels is to enrich these devices.

Users must be able to add labels on their devices and to be able to query them by labels.

### On frontend:

The creation and edition of labels can be done using the component [ChipSet](https://mudblazor.com/components/chipset#adding-and-removing-chips) within the pages of creation/details. Below an example:

![image](https://user-images.githubusercontent.com/10477425/172601476-5abfecfc-fcde-4294-9a39-b14d61ed76fb.png)

Listing pages, labels can be viewed also as a chip set  on a row detail

**Comment by kbeaugrand** [comment]
Think about the possibility to have : 
- [ ] Colors on labels
- [ ] Default labels from the device model

**Comment by hocinehacherouf** [comment]
Is blocked by #1382
