### ISSUE TITLE
Feature: Add concentrator configuration for AU915-928 Region

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#810]
**Is your feature request related to a problem? Please describe.**
I would like to create a new concentrator and configure it for a new Region : AU915-928.

**Describe the solution you'd like**
As I am able to select Europe or US configuration while i'm creating/updating a concentrator, I would like to select AU915-928 (Frequency Band for Brazil).

**Additional context**
This issue will be possible only when the iotedge-lorawan-starterkit (from Microsoft) will have add the support of this new Region. Here is the linked issue from the starterkit project :
https://github.com/Azure/iotedge-lorawan-starterkit/issues/1730

**Comment by kbeaugrand** [comment]
As discussed with the team, @adcoly do you have the possibility to manually test a version of the starter kit supporting the frequency to help the team in the implementations to make it ready to prod?
