### ISSUE TITLE
Feature: Searching a sensor easely with any part of its name

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#862]
**Is your feature request related to a problem? Please describe.**
When I'm searching a sensor, I Have to write the beginning of the sensor name to find it.

**Describe the solution you'd like**
When I'm searching a sensor, I would like to find it by writing just a part of its name

**Additional context**
![image](https://user-images.githubusercontent.com/33126264/175535940-7f9de905-4f65-4c6a-a420-7d4c0095de77.png)
![image](https://user-images.githubusercontent.com/33126264/175535997-b5a4d64e-aee8-4c38-bdee-f8083e76d212.png)

**Comment by hocinehacherouf** [comment]
Related to #567

**Comment by kbeaugrand** [comment]
Blocked by #1029, #1030 and #1031
