### ISSUE TITLE
Rename DefaultEnrollmentGroupe to DefaultEnrollmentGroup

### ISSUE THREAD

**Issue by kbeaugrand** [CGI-FR/IoT-Hub-Portal#88]
- [ ] https://github.com/michelin/i4i-iot-hub-portal/blob/5ce05e6ed22fd7a82ab5e2abdb96bd918eb806cd/src/AzureIoTHub.Portal/Server/Services/DeviceService.cs#L133

**Comment by audserraCGI** [comment]
Startup.cs file also needs to be fixed
