### ISSUE TITLE
Feature: Flaky tests must be ran multiple times to improve their chances of success

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#881]
**Is your feature request related to a problem? Please describe.**
Some unit tests on blazor views fails randomly on ci

**Describe the solution you'd like**
See https://github.com/MudBlazor/MudBlazor/blob/bfa02404dd0bd9406b5b64cb9994c9319aaa6bc1/src/MudBlazor.UnitTests/Components/BunitTest.cs#L35-L47

**Comment by kbeaugrand** [comment]
Fixed with unit tests refactoring
