### ISSUE TITLE
Bug: Research in the device list

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#893]
## Expected Behavior
I should find my device by typing the ID of the device.

## Current Behavior
It does not work when there is uppercase letter in the id.

**Comment by hocinehacherouf** [comment]
This bug occurs on searching devices and edge devices, when the device ID contains alpha characters : The backend sets the the device ID to lowercase when executing the search query.

Affected lines :

https://github.com/CGI-FR/IoT-Hub-Portal/blob/8d9b86cda2a94aea62e44c410cd20700ad82abe7/src/AzureIoTHub.Portal/Server/Services/DeviceService.cs#L64

https://github.com/CGI-FR/IoT-Hub-Portal/blob/8d9b86cda2a94aea62e44c410cd20700ad82abe7/src/AzureIoTHub.Portal/Server/Services/DeviceService.cs#L162

Solution:

Replace `deviceId, {searchText.ToLowerInvariant()}` by `deviceId, {searchText.ToLowerInvariant()}`
