### ISSUE TITLE
Bug: Command sent to the sensor badly formed

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#913]
## Expected Behavior
I should retrieve the exact payload I tried to send.

## Current Behavior
When I am looking in the LorawanNetworkSrvModule logs, the pyaload is not the same.

## Context (Environment)

**Portal version**: 2.4.0
**LoRaWAN Stack version**: 2.1.0

## Logs
- Command sent:
`0149001E001E03E8000000`

- Command seen in the logs:
`30313439303031453030314530334538303030303030`

**Comment by kbeaugrand** [comment]
This seems to be related to the LoRaWAN Starter Kit. 
@adcoly is in contact with the team in charge to that module.

**Comment by Metal-Mighty** [comment]
Reopening as it is not a LoRaWAN Starter Kit issue, it's an issue in the portal when sending the command
