### ISSUE TITLE
Feature: The new loading animation at the top of the screen is barely visible

### ISSUE THREAD

**Issue by audserraCGI** [CGI-FR/IoT-Hub-Portal#918]
When using a light theme, the global loading animation at the top of the screen is barely visible:

![Loading](https://user-images.githubusercontent.com/95615798/178744922-b8156345-19cd-476d-a6d5-25c975133e94.PNG)

We should consider using a wider loading bar/an other color.

Linked to issue : #900

**Comment by hocinehacherouf** [comment]
Proposition :
- Height: 4px
- Color: `#D3E24A` (complementary of `#594AE2`)

![loding](https://user-images.githubusercontent.com/10477425/178968739-b83cc85b-ba2e-46b4-b21d-4d86bd1a4342.gif)
