### ISSUE TITLE
Feature: Reorganize LoRaDeviceDetails and LoRaDeviceModel models

### ISSUE THREAD

**Issue by audserraCGI** [CGI-FR/IoT-Hub-Portal#969]
Currently, we have different models to manage LoRaDevice data :

- LoRaDeviceDetails is used to manage data concerning a specific LoRa device
- LoRaDeviceModel/LoRaDeviceModelBase is used to manage data concerning a general LoRa model

However, a lot of attributes are duplicated between the two models (SensorDecoder, Downlink, PreferredWindow, Deduplication, etc., for instance).

Each LoRa device already includes a reference to its corresponding model (via the DeviceDetails class it inherits from, which contains a reference to a ModelId), so the information shouldn't be duplicated.

**Comment by hocinehacherouf** [comment]
Investigation is required on the usage of duplicated properties on device

**Comment by kbeaugrand** [comment]
See expected re-organization: 

```mermaid
classDiagram
    LoRaDeviceBase <|-- LoRaDevice
    LoRaDeviceBase <|-- LoRaDeviceModel

    class LoRaDeviceBase{
      +enum Deviceclass
      +enum DeduplicationMode
      +string ...
    }
    class LoRaDeviceModel{
      +int modelId
    }
    class LoRaDevice {
      +string AppEui
      +string AppKey
      +string GatewayId
      +reported Properties
      
    }
            
```
