### ISSUE TITLE
Feature: Add sorting in columns 

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#991]
**Is your feature request related to a problem? Please describe.**
We would like to be able to sort entries in the different lists of objects: Device list, Device models, etc...

**Describe the solution you'd like**
Add sorting by clicking on the column header and with a visual icon showing how the table is sorted. 
It must be available for several columns but not always all of them, e.g., in the device list it should be available for all except Details and Delete, in Device Models only on the name, etc.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kbeaugrand** [comment]
Blocked by #1029 and #1030
